name: CQA Todoist CI
on:
  push:
    branches: [ TempoNL ]
  pull_request:
    branches: [ TempoNL ]

jobs:
  Lint:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
           node-version: '14.x'
      - run: npm ci
<<<<<<< HEAD
      - run: npm run lint
=======
      - run: npm run lint
      

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Gti checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install newman
        run: npm install newman
      - run: npm run api-test
>>>>>>> a3a2e0dbde6d8ca8c939aa6d917ca3a463584bca
