# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Github Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  runningEslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Gti checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Install node_modules
      - name: Run Lint
        run: npm ci
      - run: npm run lint
      # Print current Node.js version
      - run: node --version
      # Print current npm version
      - run: npm --version
      # Print current Git version
      - run: git --version
      
  installNewman:

    needs: runningEslint
    runs-on: ubuntu-latest
    
    steps:
      - name: Install newman
        run: npm install newman

      
  RunPOSTMANcollection:

    needs: installNewman
    runs-on: ubuntu-latest
    
    steps:   
      - name: Testing API 
        run: npm run api-testing
